[server]
# Configurações do servidor
port = 8502
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = true

[browser]
serverAddress = "0.0.0.0"
serverPort = 8502

[runner]
# Configurações do runner
fastRerun = true

[client]
# Configurações do cliente
caching = true

[mapbox]
token = ""  # Adicione seu token do Mapbox aqui se necessário

[theme]
# Tema personalizado (opcional)
base = "dark"
primaryColor = "#1f77b4"
backgroundColor = "#0b0f14"
secondaryBackgroundColor = "#1e2228"
textColor = "#e5e7eb"
font = "sans serif"
