[global]
# Configurações globais do Streamlit

[server]
# Configurações do servidor
port = 8501
headless = false
enableCORS = false
enableXsrfProtection = true

[browser]
# Configurações do navegador
gatherUsageStats = false

[theme]
# Configurações do tema (forçado para escuro)
base = "dark"
primaryColor = "#8a5cf5"
backgroundColor = "#0b0f14"
secondaryBackgroundColor = "#111827"
textColor = "#e5e7eb"
font = "sans serif"

[logger]
# Configurações de logging
level = "info"

[client]
# Configurações do cliente
showErrorDetails = true