[global]
# Configurações globais do Streamlit

[server]
# Configurações do servidor
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = true

[browser]
# Configurações do navegador
gatherUsageStats = false

[theme]
# Configurações do tema (forçado para escuro)
primaryColor = "#667eea"
backgroundColor = "#0b0f14"
secondaryBackgroundColor = "#111827"
textColor = "#e5e7eb"
font = "sans serif"

[logger]
# Configurações de logging
level = "info"

[client]
# Configurações do cliente
showErrorDetails = true