# Preencha estas chaves com seus valores reais antes de executar a aplicação.
# NUNCA faça commit deste arquivo com chaves reais em repositórios públicos.

MISTRAL_API_KEY = "O1oLoNRGwMWfSa5svv3y4lkz9ewobNKL"
GEMINI_API_KEY = "AIzaSyDbsOFkrepCdsxU0NNhLLQK8-_a24FsiKI"
