# Configurações do PriceTrack AI
# Copie este arquivo para .streamlit/secrets.toml e configure suas chaves

# Chave da API Google Gemini (OBRIGATÓRIO)
GEMINI_API_KEY = "sua_chave_api_gemini_aqui"

# Configurações SMTP para alertas por email (OPCIONAL)
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USER = "seu_email@gmail.com"
SMTP_PASSWORD = "sua_senha_app"

# Configurações adicionais (OPCIONAL)
APP_NAME = "PriceTrack AI"
APP_VERSION = "1.0.0"
DEBUG_MODE = false
MAX_PRODUCTS_PER_COMPARISON = 5
CACHE_TTL_SECONDS = 1800
