# Generated by Django 6.0 on 2025-12-04 18:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_transaction_target_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='Símbolo (Ticker)')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nome do Ativo')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Quantidade')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço de Compra')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Compra')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment', to='core.transaction', verbose_name='Transação Associada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
            },
        ),
    ]
