# Generated by Django 6.0 on 2025-12-16 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_investment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recurring',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], default='DINHEIRO', max_length=20, verbose_name='Método de Pagamento'),
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=15, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('payment_method', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], default='DINHEIRO', max_length=20, verbose_name='Método de Pagamento')),
                ('frequency', models.CharField(choices=[('DIARIO', 'Diário'), ('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal'), ('ANUAL', 'Anual')], default='MENSAL', max_length=20, verbose_name='Frequência')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('next_run_date', models.DateField(verbose_name='Próxima Execução')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Transação Recorrente',
                'verbose_name_plural': 'Transações Recorrentes',
            },
        ),
    ]
