# Generated by Django 6.0 on 2025-12-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='category_type',
            field=models.CharField(choices=[('VARIABLE', 'Renda Variável'), ('FIXED', 'Renda Fixa'), ('CURRENCY', 'Moedas')], default='VARIABLE', max_length=10, verbose_name='Tipo de Categoria'),
        ),
        migrations.AddField(
            model_name='investment',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='investment',
            name='fixed_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ex: 120 para 120% do CDI ou 10.5 para 10.5% a.a.', max_digits=5, null=True, verbose_name='Taxa (%)'),
        ),
        migrations.AddField(
            model_name='investment',
            name='index_type',
            field=models.CharField(blank=True, choices=[('CDI', 'CDI'), ('IPCA', 'IPCA'), ('PRE', 'Pré-fixado'), ('POUPANCA', 'Poupança')], max_length=10, null=True, verbose_name='Índice'),
        ),
        migrations.AddField(
            model_name='investment',
            name='tax_free',
            field=models.BooleanField(default=False, verbose_name='Isento de IR?'),
        ),
    ]
