# Generated by Django 5.1.4 on 2026-06-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_loan_iof_insurance_disbursement"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="monthly_target",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Aporte Mensal Planejado",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="insurance_monthly",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Seguro prestamista mensal fixo. Deixe 0 se não houver.",
                max_digits=10,
                verbose_name="Seguro Mensal (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="iof_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                help_text="Percentual do IOF sobre o principal. Ex: 3.0 para 3%. Deixe 0 para empréstimos sem IOF.",
                max_digits=7,
                verbose_name="IOF (%)",
            ),
        ),
    ]
