# Generated by Django 5.1.4 on 2026-09-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_min_value_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='end_date',
            field=models.DateField(blank=True, help_text='Deixe vazio para repetir indefinidamente.', null=True, verbose_name='Repetir até'),
        ),
    ]
