# Generated by Django 5.1.4 on 2026-09-27 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_recurring_transaction_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, help_text='Cor nos gráficos, ex: #6366f1. Deixe vazio para automática.', max_length=7, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='category',
            name='nature',
            field=models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('INVESTIMENTO', 'Investimento'), ('DIVIDA', 'Dívida / Empréstimo')], default='OPERACIONAL', max_length=15, verbose_name='Natureza'),
        ),
        migrations.AddField(
            model_name='loan',
            name='planned_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor que você pretende pagar por mês. Tem prioridade sobre o cálculo automático; use em empréstimos informais (0 parcelas) ou para ajustar o valor manualmente.', max_digits=15, null=True, verbose_name='Parcela combinada (R$)'),
        ),
        migrations.AddField(
            model_name='loan',
            name='register_income',
            field=models.BooleanField(default=True, help_text='Lança o valor líquido recebido (principal − IOF) como entrada na data do empréstimo.', verbose_name='Registrar o valor recebido como receita?'),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Saldo Antes'),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_payment', to='core.transaction', verbose_name='Transação'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Lançado em'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_group',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Grupo de parcelas'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Parcela nº'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total de parcelas'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.loan', verbose_name='Empréstimo'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('PARCELA', 'Parcela (cartão)'), ('RECORRENTE', 'Recorrente'), ('EMPRESTIMO', 'Empréstimo'), ('INVESTIMENTO', 'Investimento'), ('IMPORTACAO', 'Importação')], db_index=True, default='MANUAL', max_length=15, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='core.recurringtransaction', verbose_name='Recorrência de origem'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='tx_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='tx_user_created_idx'),
        ),
    ]
