# Generated by Django 5.1.4 on 2026-09-27 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_foundations'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='synced_at',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Parcelas sincronizadas em'),
        ),
        migrations.AddField(
            model_name='loandisbursement',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_disbursement', to='core.transaction', verbose_name='Transação'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='num_installments',
            field=models.IntegerField(blank=True, help_text='Obrigatório para Price e SAC. Use 0 (ou vazio) para empréstimos informais, sem prazo fixo.', null=True, verbose_name='Número de Parcelas'),
        ),
    ]
