# Generated by Django 5.1.4 on 2026-09-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_loan_sync_disbursement_tx'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='first_due_date',
            field=models.DateField(blank=True, help_text='Vencimento da primeira parcela. Vazio = no dia de vencimento do mês seguinte à data do empréstimo.', null=True, verbose_name='1ª parcela em'),
        ),
    ]
