"""casos por contato

Revision ID: 1d8272fae6bb
Revises: ca4b4c17b489
Create Date: 2026-08-12 19:04:42.209144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8272fae6bb'
down_revision: Union[str, None] = 'ca4b4c17b489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('titular', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('analise_preliminar', sa.Text(), nullable=True),
    sa.Column('score_qualificacao', sa.Integer(), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casos_lead_id'), 'casos', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_casos_lead_id'), table_name='casos')
    op.drop_table('casos')
    # ### end Alembic commands ###
