"""schema inicial

Revision ID: 205497c82fd9
Revises: 
Create Date: 2026-08-11 10:42:56.333140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205497c82fd9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('mensagens_recebidas', sa.Integer(), nullable=True),
    sa.Column('mensagens_enviadas', sa.Integer(), nullable=True),
    sa.Column('leads_criados', sa.Integer(), nullable=True),
    sa.Column('leads_qualificados', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', 'agent_id', name='uix_daily_stats_data_agent')
    )
    op.create_index('idx_daily_stats_data', 'daily_stats', ['data'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_user_id'), 'agents', ['user_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('chave', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('expira_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    op.create_table('agent_variables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('nome_variavel', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor_padrao', sa.String(length=255), nullable=True),
    sa.Column('opcoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'nome_variavel', name='uix_agent_variable_nome')
    )
    op.create_index(op.f('ix_agent_variables_agent_id'), 'agent_variables', ['agent_id'], unique=False)
    op.create_table('conversation_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('total_atendimentos', sa.Integer(), nullable=True),
    sa.Column('taxa_qualificacao', sa.Float(), nullable=True),
    sa.Column('tempo_medio_min', sa.Float(), nullable=True),
    sa.Column('mensagens_recebidas', sa.Integer(), nullable=True),
    sa.Column('mensagens_enviadas', sa.Integer(), nullable=True),
    sa.Column('leads_qualificados', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'data', name='uix_metrics_agent_data')
    )
    op.create_index('idx_metrics_data', 'conversation_metrics', ['data'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_ultima_msg', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'phone_number', name='uix_conversation_agent_phone')
    )
    op.create_index('idx_conversation_phone_number', 'conversations', ['phone_number'], unique=False)
    op.create_index(op.f('ix_conversations_agent_id'), 'conversations', ['agent_id'], unique=False)
    op.create_table('kanban_columns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('cor_hex', sa.String(length=7), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'nome', name='uix_kanban_column_agent_nome')
    )
    op.create_index(op.f('ix_kanban_columns_agent_id'), 'kanban_columns', ['agent_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status_funil', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id'),
    sa.UniqueConstraint('phone_number', name='uix_lead_phone_number')
    )
    op.create_index(op.f('ix_leads_phone_number'), 'leads', ['phone_number'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('remetente', sa.String(length=20), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('tokens_usados', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_index('idx_message_timestamp', 'messages', ['timestamp'], unique=False)
    op.create_table('function_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('nome_funcao', sa.String(length=255), nullable=False),
    sa.Column('parametros_json', sa.Text(), nullable=False),
    sa.Column('resultado_json', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_function_call_conversation_id', 'function_calls', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_function_calls_conversation_id'), 'function_calls', ['conversation_id'], unique=False)
    op.create_table('kanban_cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('column_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('data_movimentacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['kanban_columns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id')
    )
    op.create_index('idx_kanban_card_column_id', 'kanban_cards', ['column_id'], unique=False)
    op.create_table('lead_details',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('inconsistencias', sa.Text(), nullable=True),
    sa.Column('problemas_detectados', sa.Text(), nullable=True),
    sa.Column('score_qualificacao', sa.Integer(), nullable=True),
    sa.Column('dados_json', sa.Text(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id')
    )
    op.create_table('lead_timeline',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('status_anterior', sa.String(length=50), nullable=True),
    sa.Column('status_novo', sa.String(length=50), nullable=False),
    sa.Column('mudado_por', sa.String(length=36), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mudado_por'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lead_timeline_lead_id', 'lead_timeline', ['lead_id'], unique=False)
    op.create_index('idx_lead_timeline_timestamp', 'lead_timeline', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lead_timeline_timestamp', table_name='lead_timeline')
    op.drop_index('idx_lead_timeline_lead_id', table_name='lead_timeline')
    op.drop_table('lead_timeline')
    op.drop_table('lead_details')
    op.drop_index('idx_kanban_card_column_id', table_name='kanban_cards')
    op.drop_table('kanban_cards')
    op.drop_index(op.f('ix_function_calls_conversation_id'), table_name='function_calls')
    op.drop_index('idx_function_call_conversation_id', table_name='function_calls')
    op.drop_table('function_calls')
    op.drop_index('idx_message_timestamp', table_name='messages')
    op.drop_index('idx_message_conversation_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_leads_phone_number'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_kanban_columns_agent_id'), table_name='kanban_columns')
    op.drop_table('kanban_columns')
    op.drop_index(op.f('ix_conversations_agent_id'), table_name='conversations')
    op.drop_index('idx_conversation_phone_number', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_metrics_data', table_name='conversation_metrics')
    op.drop_table('conversation_metrics')
    op.drop_index(op.f('ix_agent_variables_agent_id'), table_name='agent_variables')
    op.drop_table('agent_variables')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_agents_user_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_daily_stats_data', table_name='daily_stats')
    op.drop_table('daily_stats')
    # ### end Alembic commands ###
