"""parecer preliminar no lead_details

Revision ID: ca4b4c17b489
Revises: 205497c82fd9
Create Date: 2026-08-12 17:47:08.232635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca4b4c17b489'
down_revision: Union[str, None] = '205497c82fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_details', sa.Column('analise_preliminar', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_details', 'analise_preliminar')
    # ### end Alembic commands ###
