# Generated by Django 5.1.15 on 2026-06-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('aberto', 'Em Aberto'), ('correcao', 'Aguardando Correção'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='rascunho', max_length=20),
        ),
    ]
