# Generated by Django 5.1.15 on 2026-06-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_add_status_correcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='categoria',
            field=models.CharField(choices=[('ti', 'TI / Tecnologia'), ('rh', 'Recursos Humanos'), ('marketing', 'Marketing'), ('operacional', 'Operacional'), ('infraestrutura', 'Infraestrutura / Facilities'), ('financeiro', 'Financeiro'), ('limpeza', 'Limpeza / Higiene'), ('outros', 'Outros')], default='outros', max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='prazo_necessario',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
